### ISSUE TITLE
installing ros packages

### ISSUE THREAD

**Issue by blankered** [UAVenture/ros-setups#2]
How do I install other ros packages such as hector slam? I keep running into problems where apt-get cannot not find the package using the command "sudo apt-get install ros-indigo-hector-slam".

**Comment by SimonWilks** [comment]
I imagine you will need to build this from source as well as this package
won't be available for ubilunux.

**Comment by dreamkeep** [comment]
hi sjwilks
This file "http://archive.raspbian.org/raspbian.public.key"  is not exist now,

**Comment by SimonWilks** [comment]
The installation guide it is based on no longer seems to have it: http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Indigo%20on%20Raspberry%20Pi

Can you try just skipping that step?

**Comment by dreamkeep** [comment]
hi simonwilks,
    It is a error like  this when I run the command :
sh -c 'echo "deb-src http://mirrordirector.raspbian.org/raspbian/ testing main contrib non-free rpi" >> /etc/apt/sources.list'

sh -c 'echo "deb http://http.debian.net/debian wheezy-backports main" >> /etc/apt/sources.list'

apt-get -y update

Fetched 3,065 B in 40s (75 B/s)  
Reading package lists... Done
W: GPG error: http://mirrordirector.raspbian.org testing Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9165938D90FDDD2E
W: Duplicate sources.list entry http://http.debian.net/debian/ wheezy-backports/main i386 Packages (/var/lib/apt/lists/http.debian.net_debian_dists_wheezy-backports_main_binary-i386_Packages)

**Comment by SimonWilks** [comment]
@dreamkeep the raspian public key http://archive.raspbian.org/raspbian.public.key returned on the evening of the 24th. It should work now. I'll setup a second new Edison tomorrow and verify this myself.

**Comment by dreamkeep** [comment]
@SimonWilks  I try that this command can fix that error:

gpg --keyserver keys.gnupg.net --recv-key 9165938D90FDDD2E
gpg -a --export 9165938D90FDDD2E |  apt-key add -

**Comment by dreamkeep** [comment]
@sjwilks this tutorial have many errors when we setup ros in ubilinux on edison now, so can you give us a new tutorial? thanks a lot.

**Comment by SimonWilks** [comment]
@dreamkeep I just ran through the full setup and updated the installation instructions and the setup script. I need to run through it once more tomorrow as I had to fix stuff mid-stream but it should work now.

The latest ubilinux gives even less space on the root partition so it would have run out. There is also an ongoing DOS attack on github causing downloads in the installer to fail. I have now added a retry which seems to work.
